---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: corfu-exporter
  labels:
    name: corfu-exporter
    app: corfu-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: corfu-exporter
        app: corfu-exporter
    spec:
      containers:
        - image: pzaytsev/own:exporter
          name: corfu-exporter
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: corfu-exporter
  name: corfu-exporter-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: corfu-exporter
  selector:
    app: corfu-exporter
